wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.4
    framework: huggingface
    huggingface_version: 4.38.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721287566
    t:
      1:
      - 1
      - 9
      - 11
      - 49
      - 55
      - 103
      - 105
      2:
      - 1
      - 9
      - 11
      - 49
      - 53
      - 55
      - 103
      - 105
      3:
      - 1
      - 7
      - 13
      - 15
      - 23
      - 66
      4: 3.10.12
      5: 0.17.4
      6: 4.38.1
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
max_epochs:
  desc: null
  value: 50
batch_size:
  desc: null
  value: 16
lr:
  desc: null
  value: 0.001
sampling_frequency:
  desc: null
  value: 16000
dBNoise:
  desc: null
  value: null
kernels:
  desc: null
  value: freq
n_grus:
  desc: null
  value: 2
features_set:
  desc: null
  value: all
att_conf:
  desc: null
  value:
  - Nothing
  - onSpec
  - onAll
